version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/02-frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/03-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
