import React, { useState } from 'react';
import {
  Sparkles,
  GitCommit,
  CheckCheck,
  Trash2,
  FileCode2,
  Plus,
  Minus,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import { gitApi } from '../../api';
import { useToast } from '../common/Toast';
import { Spinner } from '../common/Spinner';
import { GitStatus, AICommitSuggestion } from '../../types/git';

interface CommitGeneratorProps {
  projectId: string;
  status: GitStatus | null;
  onCommitSuccess: () => void;
  onStageChange: () => void;
}

export const CommitGenerator: React.FC<CommitGeneratorProps> = ({
  projectId,
  status,
  onCommitSuccess,
  onStageChange,
}) => {
  const [commitMessage, setCommitMessage] = useState('');
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [isCommitting, setIsCommitting] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<AICommitSuggestion | null>(null);
  const [showDiscardConfirm, setShowDiscardConfirm] = useState(false);
  const [showFileList, setShowFileList] = useState(true);
  const { toast } = useToast();

  const stagedFiles = status?.staged || [];
  const modifiedFiles = status?.modified || [];
  const untrackedFiles = status?.untracked || [];
  const allUnstaged = [...modifiedFiles, ...untrackedFiles];

  // Stage All
  const handleStageAll = async () => {
    try {
      await gitApi.stage(projectId, ['*']);
      toast('All changes staged', 'success');
      onStageChange();
    } catch (err: any) {
      toast(err.message || 'Failed to stage files', 'error');
    }
  };

  // Unstage All
  const handleUnstageAll = async () => {
    try {
      await gitApi.unstage(projectId, ['*']);
      toast('All files unstaged', 'success');
      onStageChange();
    } catch (err: any) {
      toast(err.message || 'Failed to unstage files', 'error');
    }
  };

  // Stage Single File
  const handleStageFile = async (filePath: string) => {
    try {
      await gitApi.stage(projectId, [filePath]);
      onStageChange();
    } catch (err: any) {
      toast(err.message || 'Failed to stage file', 'error');
    }
  };

  // Unstage Single File
  const handleUnstageFile = async (filePath: string) => {
    try {
      await gitApi.unstage(projectId, [filePath]);
      onStageChange();
    } catch (err: any) {
      toast(err.message || 'Failed to unstage file', 'error');
    }
  };

  // Discard all unstaged changes
  const handleDiscardAll = async () => {
    try {
      await gitApi.discard(projectId, ['*']);
      toast('Unstaged changes discarded', 'success');
      setShowDiscardConfirm(false);
      onStageChange();
    } catch (err: any) {
      toast(err.message || 'Failed to discard changes', 'error');
    }
  };

  // AI Conventional Commit Generator
  const handleGenerateAICommit = async () => {
    const filesToAnalyze = stagedFiles.length > 0 ? stagedFiles : allUnstaged;
    if (filesToAnalyze.length === 0) {
      toast('No modified or staged files to analyze for commit', 'error');
      return;
    }

    setIsGeneratingAI(true);
    try {
      const res = await gitApi.generateCommitMessage(projectId, {
        files: filesToAnalyze,
        context_hint: 'Routine workspace implementation',
      });
      if (res.success && res.data) {
        setAiSuggestion(res.data);
        setCommitMessage(res.data.full_conventional || res.data.message);
        toast('Conventional commit generated by Gemini!', 'success');
      }
    } catch (err: any) {
      toast(err.message || 'AI Commit generation failed', 'error');
    } finally {
      setIsGeneratingAI(false);
    }
  };

  // Commit
  const handleCommit = async () => {
    if (!commitMessage.trim() || isCommitting) return;

    if (stagedFiles.length === 0 && allUnstaged.length > 0) {
      // Auto-stage all before committing if none explicitly staged
      await gitApi.stage(projectId, ['*']);
    }

    setIsCommitting(true);
    try {
      const res = await gitApi.commit(projectId, commitMessage.trim());
      if (res.success) {
        toast('Changes committed to Git repository!', 'success');
        setCommitMessage('');
        setAiSuggestion(null);
        onCommitSuccess();
      }
    } catch (err: any) {
      toast(err.message || 'Commit failed', 'error');
    } finally {
      setIsCommitting(false);
    }
  };

  return (
    <div
      id="commit-generator-panel"
      style={{
        background: 'rgba(15, 23, 42, 0.65)',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius-md)',
        padding: '12px 14px',
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
      }}
    >
      {/* Top Header with Staging Actions */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 6 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <GitCommit size={14} color="#38bdf8" />
          <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--color-text-primary)' }}>
            Stage & Commit Engine
          </span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
          {allUnstaged.length > 0 && (
            <button
              id="git-stage-all-btn"
              onClick={handleStageAll}
              title="Stage all changes"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 4,
                background: 'rgba(16, 185, 129, 0.15)',
                border: '1px solid rgba(16, 185, 129, 0.3)',
                borderRadius: 4,
                padding: '3px 8px',
                fontSize: '11px',
                color: '#34d399',
                cursor: 'pointer',
                fontWeight: 500,
              }}
            >
              <Plus size={11} />
              <span>Stage All</span>
            </button>
          )}

          {stagedFiles.length > 0 && (
            <button
              id="git-unstage-all-btn"
              onClick={handleUnstageAll}
              title="Unstage all staged files"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 4,
                background: 'rgba(239, 68, 68, 0.15)',
                border: '1px solid rgba(239, 68, 68, 0.3)',
                borderRadius: 4,
                padding: '3px 8px',
                fontSize: '11px',
                color: '#f87171',
                cursor: 'pointer',
                fontWeight: 500,
              }}
            >
              <Minus size={11} />
              <span>Unstage All</span>
            </button>
          )}

          {allUnstaged.length > 0 && !showDiscardConfirm && (
            <button
              onClick={() => setShowDiscardConfirm(true)}
              title="Discard all working tree changes"
              style={{
                background: 'transparent',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                borderRadius: 4,
                padding: '3px 6px',
                color: 'var(--color-text-muted)',
                cursor: 'pointer',
              }}
            >
              <Trash2 size={11} />
            </button>
          )}
        </div>
      </div>

      {/* Discard Confirmation Dialog */}
      {showDiscardConfirm && (
        <div
          style={{
            background: 'rgba(239, 68, 68, 0.15)',
            border: '1px solid rgba(239, 68, 68, 0.4)',
            borderRadius: 6,
            padding: '8px 10px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 6,
            fontSize: '11px',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#fca5a5' }}>
            <AlertTriangle size={13} />
            <span>Discard all unstaged working tree changes?</span>
          </div>
          <div style={{ display: 'flex', gap: 4 }}>
            <button
              onClick={handleDiscardAll}
              style={{
                background: '#ef4444',
                color: '#fff',
                border: 'none',
                borderRadius: 3,
                padding: '2px 8px',
                fontSize: '10px',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              Discard
            </button>
            <button
              onClick={() => setShowDiscardConfirm(false)}
              style={{
                background: 'transparent',
                color: 'var(--color-text-muted)',
                border: '1px solid rgba(255, 255, 255, 0.2)',
                borderRadius: 3,
                padding: '2px 6px',
                fontSize: '10px',
                cursor: 'pointer',
              }}
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Collapsible File List (Staged vs Unstaged) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
        <button
          onClick={() => setShowFileList(!showFileList)}
          style={{
            background: 'none',
            border: 'none',
            color: 'var(--color-text-muted)',
            fontSize: '11px',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 4,
            padding: 0,
          }}
        >
          {showFileList ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
          <span>
            Changes: {stagedFiles.length} staged, {allUnstaged.length} unstaged
          </span>
        </button>

        {showFileList && (
          <div
            style={{
              background: 'rgba(0, 0, 0, 0.3)',
              borderRadius: 6,
              padding: '6px 8px',
              maxHeight: 120,
              overflowY: 'auto',
              display: 'flex',
              flexDirection: 'column',
              gap: 4,
              fontSize: '11px',
            }}
          >
            {stagedFiles.map((file) => (
              <div
                key={`staged_${file}`}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: 6,
                  color: '#34d399',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 5, overflow: 'hidden' }}>
                  <FileCode2 size={12} style={{ flexShrink: 0 }} />
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {file}
                  </span>
                  <span style={{ fontSize: '9px', opacity: 0.8 }}>(staged)</span>
                </div>
                <button
                  onClick={() => handleUnstageFile(file)}
                  title="Unstage"
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#f87171',
                    cursor: 'pointer',
                    padding: 0,
                  }}
                >
                  <Minus size={11} />
                </button>
              </div>
            ))}

            {allUnstaged.map((file) => (
              <div
                key={`unstaged_${file}`}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: 6,
                  color: modifiedFiles.includes(file) ? '#38bdf8' : '#94a3b8',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 5, overflow: 'hidden' }}>
                  <FileCode2 size={12} style={{ flexShrink: 0 }} />
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {file}
                  </span>
                  <span style={{ fontSize: '9px', opacity: 0.8 }}>
                    {modifiedFiles.includes(file) ? '(modified)' : '(untracked)'}
                  </span>
                </div>
                <button
                  onClick={() => handleStageFile(file)}
                  title="Stage"
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#34d399',
                    cursor: 'pointer',
                    padding: 0,
                  }}
                >
                  <Plus size={11} />
                </button>
              </div>
            ))}

            {stagedFiles.length === 0 && allUnstaged.length === 0 && (
              <div style={{ color: 'var(--color-text-muted)', textAlign: 'center', padding: '4px 0' }}>
                Working tree clean.
              </div>
            )}
          </div>
        )}
      </div>

      {/* AI Conventional Commit Action */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <button
          id="git-ai-commit-generator-btn"
          onClick={handleGenerateAICommit}
          disabled={isGeneratingAI}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 5,
            background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.2), rgba(56, 189, 248, 0.2))',
            border: '1px solid rgba(139, 92, 246, 0.4)',
            borderRadius: 4,
            padding: '4px 10px',
            fontSize: '11px',
            color: '#c084fc',
            fontWeight: 600,
            cursor: isGeneratingAI ? 'wait' : 'pointer',
          }}
        >
          <Sparkles size={12} />
          <span>{isGeneratingAI ? 'Synthesizing with Gemini...' : 'AI Conventional Commit'}</span>
        </button>

        {aiSuggestion && (
          <span
            style={{
              fontSize: '10px',
              color: '#38bdf8',
              background: 'rgba(56, 189, 248, 0.1)',
              padding: '2px 6px',
              borderRadius: 4,
            }}
          >
            type: {aiSuggestion.type} ({aiSuggestion.scope})
          </span>
        )}
      </div>

      {/* Commit Textarea */}
      <textarea
        id="git-commit-message-input"
        rows={2}
        placeholder="feat(core): concise conventional commit description..."
        value={commitMessage}
        onChange={(e) => setCommitMessage(e.target.value)}
        style={{
          width: '100%',
          background: 'rgba(0, 0, 0, 0.35)',
          border: '1px solid var(--color-border)',
          borderRadius: 4,
          padding: '6px 8px',
          fontSize: '12px',
          color: 'var(--color-text-primary)',
          fontFamily: 'monospace',
          resize: 'vertical',
          outline: 'none',
        }}
      />

      {/* Commit Button */}
      <button
        id="git-commit-submit-btn"
        onClick={handleCommit}
        disabled={isCommitting || !commitMessage.trim()}
        style={{
          background: !commitMessage.trim() ? 'rgba(56, 189, 248, 0.2)' : 'var(--color-accent)',
          border: 'none',
          borderRadius: 4,
          padding: '6px 12px',
          fontSize: '12px',
          fontWeight: 600,
          color: '#fff',
          cursor: !commitMessage.trim() || isCommitting ? 'not-allowed' : 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 6,
        }}
      >
        {isCommitting ? <Spinner size={13} /> : <CheckCheck size={13} />}
        <span>Commit to {status?.branch || 'main'}</span>
      </button>
    </div>
  );
};
