name: DEVOS CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          cd 03-backend
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio httpx

      - run: pytest

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: |
          cd 02-frontend
          npm install
          npm run build
